name: Run Market Scanner

on:
  schedule:
    # 8:00 AM to 11:00 AM EST (every 1 minute)
    - cron: "*/1 13-15 * * 1-5"  # 13:00 to 15:59 UTC
    - cron: "0 16 * * 1-5"       # 11:00 AM sharp

    # 11:00 AM to 3:00 PM EST (every 2 minutes)
    - cron: "*/2 16-19 * * 1-5"  # 16:00 to 19:59 UTC
  workflow_dispatch:  # allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install requests pandas yfinance

      - name: Run Market Scanner
        run: python sqlite_stock_tracker.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
